// Generated by CoffeeScript 1.4.0
(function() {

  define(["jquery", "backbone", "views/header", "views/home", "views/designs", "views/design"], function($, Backbone, HeaderView, HomeView, DesignsView, DesignView) {
    var Router;
    Router = Backbone.Router.extend({
      initialize: function() {
        var headerView;
        Backbone.history.start({
          pushState: true
        });
        headerView = new HeaderView;
        return headerView.render();
      },
      routes: {
        'design': 'navDesigns',
        'design/:slug/:id': 'navDesign',
        'code': 'navCode',
        'speak': 'navSpeak',
        'write': 'navWrite',
        "*actions": "defaultAction"
      },
      defaultAction: function() {
        if (!this.homeView) {
          this.homeView = new HomeView;
        }
        this.homeView.render();
        return $('#content').html(this.homeView.el);
      },
      navDesigns: function() {
        if (!this.designsView) {
          this.designsView = new DesignsView;
        }
        this.designsView.render();
        return $('#content').html(this.designsView.el);
      },
      navDesign: function(slug, id) {
        if (!this.designView || this.designView.id !== id) {
          this.designView = new DesignView({
            id: id
          });
        }
        this.designView.render();
        return $('#content').html(this.designView.el);
      },
      navCode: function() {
        return window.location.href = 'http://www.github.com/garthdb';
      },
      navSpeak: function() {
        return window.location.href = 'http://lanyrd.com/profile/garthdb/';
      },
      navWrite: function() {
        return console.log('list Write');
      }
    });
    return Router;
  });

}).call(this);
