// Generated by CoffeeScript 1.4.0
(function() {

  define(['backbone'], function(Backbone) {
    var ProjectModel;
    ProjectModel = Backbone.Model.extend({
      defaults: {}
    });
    return ProjectModel;
  });

}).call(this);
