// Generated by CoffeeScript 1.4.0
(function() {

  define(['backbone'], function(Backbone) {
    var SessionModel;
    SessionModel = Backbone.Model.extend({
      defaults: {}
    });
    return SessionModel;
  });

}).call(this);
